# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemesSiteBuilder?tab=readme-ov-file#theme-configuration
name = "PolyRhythmic"
license = "MIT"
licenselink = "https://github.com/wonyoung-jang/hugo-PolyRhythmic/blob/main/LICENSE"
description = "A fast, lightweight Material Design 3 Hugo theme"
homepage = "https://github.com/wonyoung-jang/hugo-PolyRhythmic"
demosite = "https://wonyoungjang.org/hugo-PolyRhythmic-demo"
tags = [
  "blog",
  "company",
  "material-design",
  "responsive",
  "personal",
  "customizable",
  "dark",
  "light",
  "portfolio",
  "docs",
  "archive",
  "contact",
  "search",
  "gallery",
  "logseq"
]
features = [
  "material-design-3",
  "responsive",
  "light",
  "dark",
  "customizable-color ",
  "fast-loading-times",
  "SEO-optimized",
  "search",
  "archive",
  "gallery",
  "contact",
  "mobile-friendly",
  "social-media-integration",
  "multi-language-support",
  "syntax-highlighting",
  "logseq"
]
[author]
  name = "Wonyoung Jang"
  homepage = "https://wonyoungjang.org"
